### ISSUE TITLE
class diagram

### ISSUE THREAD

**Issue by Manniche1234** [saabendtsen/2.SemesterFlow1-Bank#7]
https://lucid.app/lucidchart/14746d60-1723-4dd4-8248-02601adccbae/view?page=.Q4MUjXso07N#?folder_id=home&browser=icon

https://lucid.app/lucidchart/invitations/accept/c16cfda6-15f0-4363-8db9-a8773cb57dac

**Comment by saabendtsen** [comment]
Class diagram

https://lucid.app/lucidchart/invitations/accept/c16cfda6-15f0-4363-8db9-a8773cb57dac
